### ISSUE TITLE
Use API key instead of creating an AWS IAM user

### ISSUE THREAD

**Issue by zmully** [mapbox/hookshot#14]
From reading the template, it looks like the AWS IAM user is only created to generate a secret key. While the user has no permissions, generally abusing IAM users like this should be avoided, and future scheduled IAM clean ups would most likely target such users for immediate deletion. 

API Gateway has a key service built-in, and regardless of whether or not you use the API key to restrict access via the native API gateway key validation, or build the API key validation into your function, it's preferable to creating an IAM user for this.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html

**Comment by rclark** [comment]
:+1: as long as you can create the the API key without attaching it to a stage I think it'd work well.
