### ISSUE TITLE
Can I access $context in my API?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/hookshot#6]
I would like to access [the `$context` variable](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference) in order to pass the source IP address to my Lambda function.

Can this be done? It seems like maybe I'd need to add it to https://github.com/mapbox/hookshot/blob/4dd7e54e7733e2e74c32cafe58c131a925c7a7f2/index.js#L167 somehow, right? Any helpful ideas?

**Comment by emilymdubois** [comment]
@davidtheclark you definitely have access to the `$context` variable since it's currently being used in the request template to pass the HTTP method back to the Lambda function. This should be possible with something like:

```
'application/json': "{\"headers\":\"$input.params()\",\"ip\":\"$context.identity.sourceIp\",\"method\":\"$context.httpMethod\",\"body\":$input.json('$')}" 
```

⚠️  You may not notice your new `ip` property being returned if you perform a simple CloudFormation update. It may require deleting and recreating your stack in order to see your changes until https://github.com/mapbox/hookshot/issues/9 lands.

**Comment by davidtheclark** [comment]
@emilymdubois: I can do this with my own CloudFormation resources, but if I'm using hookshot to create the API Gateway, I'd need to sneak in and mutate the object that hookshot returned in order to change that line of code, right? 

I wonder if a parameter should be added to hookshot allowing the user to specify other things that should show up in the response body JSON.

**Comment by rclark** [comment]
@emilymdubois do you have an example of how we could change https://github.com/mapbox/hookshot/blob/master/index.js#L175 to expose the entire context object on `.passthrough()`?

This would be nice to roll up into a breaking version alongside #11

**Comment by emilymdubois** [comment]
@rclark I haven't experimented with passing the entire `$context` object back. I only did this with the `$input` variable, and I think https://github.com/mapbox/hookshot/pull/5/commits/18a0256c33b5e0e783d85c36cd26f3ebaaa80b67 was on the right track.

**Comment by rclark** [comment]
I think the next thing to investigate is the [API Gateway proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html), which is designed to be a direct passthrough from an HTTP request to a lambda function.
