### ISSUE TITLE
CF template with multiple webhooks would have naming collisions

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/hookshot#7]
The generic resource names like `"WebhookApi"` mean that you can only use hookshot *once* within any given CloudFormation template, right? (Otherwise, one webhook's resources would override the other's.)

Am right in thinking there are reasons you might want to have *multiple* webhooks within a single template — or is that bad thinking? If so, maybe we can scope the resource names to fit the specific Lambda function?

**Comment by vincentsarago** [comment]
> or is that bad thinking?

@davidtheclark I'm 👌 with you on this,  (e.g different lambda function for different events).
