### ISSUE TITLE
Replace AWS::ApiGateway::Deployment name on updates

### ISSUE THREAD

**Issue by emilymdubois** [mapbox/hookshot#9]
When I was updating the [request template](https://github.com/mapbox/hookshot/blob/4dd7e54e7733e2e74c32cafe58c131a925c7a7f2/index.js#L166-L168) for the API Gateway passthrough method, I noticed that the method was not updating between CloudFormation updates. The updates only went into effect if I deleted and recreated the stack.

I think this can be avoided by creating a random resource name each time the stack is updated. This forces the original resource to be deleted, and the new resource to be created.

**Comment by davidtheclark** [comment]
I was also having `StageName` problems when trying to update the stack. Errors like this: `16:28:04Z us-east-1: CREATE_FAILED Deploymentbdcec9d2: StageDescription cannot be specified when stage referenced by StageName already exists`. The way that I evaded these, in the end, was to use the random deployment name as part of the deployment's stage name — so it also changed with each update.

**Comment by rclark** [comment]
Closed by #10
